{{- if and .Values.validatingWebhook.enabled .Values.validatingWebhook.certManager.injectSecret }}
apiVersion: {{ .Values.validatingWebhook.certManager.apiVersion }}
kind: Certificate
metadata:
  name: kms-vault-validating-webhook
spec:
  secretName: kms-vault-validating-webhook
  duration: {{ .Values.validatingWebhook.certManager.duration }}
  renewBefore: {{ .Values.validatingWebhook.certManager.renewBefore }}
  commonName: kms-vault-validating-webhook
  dnsNames:
  - kms-vault-validating-webhook
  - kms-vault-validating-webhook.{{ .Release.Namespace }}
  - kms-vault-validating-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ .Values.validatingWebhook.certManager.issuerRef.name }}
    kind: {{ .Values.validatingWebhook.certManager.issuerRef.kind }}
{{- end }}