{{- if .Values.validatingWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kms-vault-validating-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: kms-vault-validating-webhook
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: https
  selector:
    app: kms-vault-validating-webhook
{{- end }}