{{- if .Values.validatingWebhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kms-vault-validating-webhook
  labels:
    app: kms-vault-validating-webhook
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: https
  selector:
    name: kms-vault-operator
{{- end }}