{{- if .Values.validatingWebhookSidecar.enabled }}
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: kms-vault-validating-webhook
  {{- if .Values.validatingWebhookSidecar.certManager.injectSecret }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/kms-vault-validating-webhook
  {{- end }}
webhooks:
- name: kms-vault-validating-webhook.patoarvizu.dev
  rules:
  - apiGroups:
    - k8s.patoarvizu.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kmsvaultsecrets
    - partialkmsvaultsecrets
  failurePolicy: {{ .Values.validatingWebhookSidecar.failurePolicy }}
  clientConfig:
    caBundle: {{ .Values.validatingWebhookSidecar.caBundle }}
    service:
      namespace: {{ .Release.Namespace }}
      name: kms-vault-validating-webhook
  namespaceSelector:
    matchExpressions:
    {{- range $i, $val := .Values.validatingWebhookSidecar.namespaceSelectorExpressions }}
    - key: {{ $val.key }}
      operator: {{ $val.operator }}
    {{- end -}}
{{- end }}