{{- if .Values.validatingWebhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-vault-validating-webhook
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kms-vault-validating-webhook
  template:
    metadata:
      labels:
        app: kms-vault-validating-webhook
    {{- if .Values.validatingWebhook.podAnnotations }}
      annoations: {{ toYaml .Values.validatingWebhook.podAnnotations | nindent 6 }}
    {{- end }}
    spec:
      containers:
      - name: kms-vault-validating-webhook
        image: patoarvizu/kms-vault-operator:{{ .Values.validatingWebhook.imageVersion }}
        imagePullPolicy: {{ .Values.validatingWebhook.imagePullPolicy }}
        command:
        - /kms-vault-validating-webhook
        - -tls-cert-file
        - {{ .Values.validatingWebhook.tls.mountPath }}/tls.crt
        - -tls-key-file
        - {{ .Values.validatingWebhook.tls.mountPath }}/tls.key
        ports:
        - name: https
          containerPort: 4443
        volumeMounts:
        - name: tls
          mountPath: {{ .Values.validatingWebhook.tls.mountPath }}
        env:
        {{- toYaml .Values.aws.iamCredentialsSecrets | nindent 8 }}
        - name: AWS_REGION
          value: {{ .Values.aws.region }}
      volumes:
      - name: tls
        secret:
          {{- if .Values.validatingWebhook.certManager.injectSecret }}
          secretName: kms-vault-validating-webhook
          {{- else }}
          secretName: {{ .Values.validatingWebhook.tls.secretName }}
          {{- end }}
{{- end }}