# permissions for end users to edit kmsvaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmsvaultsecret-editor-role
rules:
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets/status
  verbs:
  - get
