# permissions for end users to view kmsvaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kmsvaultsecret-viewer-role
rules:
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - kmsvaultsecrets/status
  verbs:
  - get
