# permissions for end users to edit partialkmsvaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partialkmsvaultsecret-editor-role
rules:
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - partialkmsvaultsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - partialkmsvaultsecrets/status
  verbs:
  - get
