# permissions for end users to view partialkmsvaultsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: partialkmsvaultsecret-viewer-role
rules:
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - partialkmsvaultsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.patoarvizu.dev
  resources:
  - partialkmsvaultsecrets/status
  verbs:
  - get
