apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms-vault-operator
  template:
    metadata:
      labels:
        name: kms-vault-operator
    spec:
      serviceAccountName: kms-vault-operator
      containers:
        - name: kms-vault-operator
          # Replace this with the built image name
          image: patoarvizu/kms-vault-operator:latest
          command:
          - kms-vault-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kms-vault-operator"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: us-east-1
            - name: VAULT_ADDR
              value: "https://vault:8200"
            - name: VAULT_SKIP_VERIFY
              value: "true"
        - name: kms-vault-validating-webhook
          image: patoarvizu/kms-vault-operator:latest
          command:
          - kms-vault-validating-webhook
          - -tls-cert-file
          - /tls/tls.crt
          - -tls-key-file
          - /tls/tls.key
          ports:
          - name: https
            containerPort: 4443
          - name: metrics
            containerPort: 8081
          volumeMounts:
            - name: tls
              mountPath: /tls
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: us-east-1
      volumes:
      - name: tls
        secret:
          secretName: kms-vault-validating-webhook

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kms-vault-validating-webhook
spec:
  secretName: kms-vault-validating-webhook
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: kms-vault-validating-webhook
  dnsNames:
  - kms-vault-validating-webhook
  - kms-vault-validating-webhook.default
  - kms-vault-validating-webhook.default.svc
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer

---

apiVersion: v1
kind: Service
metadata:
  name: kms-vault-validating-webhook
  labels:
    app: kms-vault-validating-webhook
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: https
  selector:
    name: kms-vault-operator

---

kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1beta1
metadata:
  name: kms-vault-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/kms-vault-validating-webhook
webhooks:
- name: kms-vault-validating-webhook.patoarvizu.dev
  rules:
  - apiGroups:
    - k8s.patoarvizu.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kmsvaultsecrets
    - partialkmsvaultsecrets
  failurePolicy: Fail
  clientConfig:
    caBundle: Cg==
    service:
      namespace: default
      name: kms-vault-validating-webhook
  namespaceSelector:
    matchExpressions:
    - key: kms-vault-operator
      operator: DoesNotExist